modLoader="javafml"
loaderVersion="[25,)"
license="MIT License"
issueTrackerURL="https://github.com/zlainsama/LainHelper/issues"
displayURL="https://github.com/zlainsama/LainHelper"
#logoFile=""
credits=""
authors="zlainsama"
[[mods]]
modId="lainhelper"
version="${file.jarVersion}"
displayName="LainHelper"
#updateJSONURL=""
description='''
'''
[[dependencies.lainhelper]]
modId="forge"
mandatory=true
versionRange="[32.0.67,)"
ordering="NONE"
side="SERVER"