package lain.mods.helper;

import java.util.Arrays;
import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.passive.EntityTameable;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraftforge.common.Configuration;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.ForgeSubscribe;
import net.minecraftforge.event.entity.living.LivingAttackEvent;
import net.minecraftforge.event.entity.living.LivingHurtEvent;
import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;

public class LainHelper extends DummyModContainer
{

    public class a
    {

        private a()
        {
            MinecraftForge.EVENT_BUS.register(this);
        }

        @ForgeSubscribe
        public void b(LivingAttackEvent event)
        {
            String a = event.source.getDamageType();
            if (checkOwner(event.entity))
            {
                if ("fall".equalsIgnoreCase(a))
                    event.setCanceled(true);
                else if ("arrow".equalsIgnoreCase(a))
                    event.setCanceled(true);
                else if (event.source.isFireDamage() || event.source.isMagicDamage() || "wither".equalsIgnoreCase(a))
                    event.setCanceled(true);
            }
        }

        @ForgeSubscribe
        public void b(LivingHurtEvent event)
        {
            String a = event.source.getDamageType();
            Entity b = event.source.getEntity();
            if (checkOwner(event.entity))
            {
                if (event.source.isExplosion())
                    event.ammount *= 0.15F;
                else
                    event.ammount *= 0.50F;
            }
            else if (checkOwner(b))
            {
                if ("arrow".equalsIgnoreCase(a))
                    event.ammount *= 2.00F;
                else if (b == event.source.getSourceOfDamage())
                {
                    event.ammount *= 1.50F;
                    if (b instanceof EntityLivingBase)
                    {
                        EntityLivingBase c = (EntityLivingBase) b;
                        if (c.getHealth() < c.getMaxHealth())
                        {
                            int d = b.hurtResistantTime;
                            c.heal(Math.min(event.ammount * 0.15F, c.getMaxHealth() * 0.30F));
                            b.hurtResistantTime = d;
                        }
                    }
                }
            }
        }
    }

    public static int idBlockWaterCube;
    public static int idBlockCobbleCube;

    public static Block blockWaterCube;
    public static Block blockCobbleCube;

    public static int customLANPort;
    public static boolean enableHelperCommands;
    public static boolean sunlightDebuff;
    public static boolean vampirePower;

    public static CommonProxy proxy;

    private static boolean checkOwner(Object obj)
    {
        if (obj instanceof String)
            return "zlainsama".equalsIgnoreCase((String) obj);
        if (obj instanceof EntityPlayer)
            return checkOwner(((EntityPlayer) obj).username);
        if (obj instanceof EntityTameable)
        {
            EntityTameable tameable = (EntityTameable) obj;
            return tameable.isTamed() && checkOwner(tameable.getOwnerName());
        }
        return false;
    }

    public LainHelper()
    {
        super(new ModMetadata());
        getMetadata();
    }

    @Override
    public ModMetadata getMetadata()
    {
        ModMetadata md = super.getMetadata();
        md.modId = "LainHelper";
        md.name = "LainHelper";
        md.version = "1.6.x-v32";
        md.authorList = Arrays.asList("zlainsama");
        md.autogenerated = false;
        return md;
    }

    @Subscribe
    public void init(FMLPreInitializationEvent event)
    {
        proxy = event.getSide().isClient() ? new ClientProxy() : new CommonProxy();
        try
        {
            Configuration config = new Configuration(event.getSuggestedConfigurationFile());

            idBlockWaterCube = config.getBlock("blockWaterCube", 3761).getInt(3761);
            idBlockCobbleCube = config.getBlock("blockCobbleCube", 3762).getInt(3762);
            customLANPort = config.get(Configuration.CATEGORY_GENERAL, "CustomLANPort", 25565).getInt(25565);
            enableHelperCommands = config.get(Configuration.CATEGORY_GENERAL, "EnableHelperCommands", true).getBoolean(true);
            sunlightDebuff = config.get(Configuration.CATEGORY_GENERAL, "SunlightDebuff", false).getBoolean(false);
            vampirePower = config.get(Configuration.CATEGORY_GENERAL, "VampirePower", false).getBoolean(false);

            config.save();
        }
        catch (Exception e)
        {
            event.getModLog().severe(String.format("ERROR loading config: %s", e.toString()));
        }
    }

    @Subscribe
    public void load(FMLInitializationEvent event)
    {
        new a();
        proxy.load(event);
    }

    @Subscribe
    public void onServerStarting(FMLServerStartingEvent event)
    {
        proxy.load(event);
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller)
    {
        bus.register(this);
        return true;
    }

}
