package lain.mods.helper;

import java.util.Arrays;
import net.minecraft.block.Block;
import net.minecraftforge.common.Configuration;
import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.event.FMLServerStoppingEvent;

public class LainHelper extends DummyModContainer
{

    public static int idBlockWaterCube;
    public static int idBlockCobbleCube;

    public static Block blockWaterCube;
    public static Block blockCobbleCube;

    public static int customLANPort;
    public static boolean enableHelperCommands;
    public static boolean overworldHomeOnly;
    public static boolean sunlightDebuff;
    public static boolean vampirePower;
    public static boolean killingSwords;

    public static CommonProxy proxy;

    public LainHelper()
    {
        super(new ModMetadata());
        getMetadata();
    }

    @Override
    public ModMetadata getMetadata()
    {
        ModMetadata md = super.getMetadata();
        md.modId = "LainHelper";
        md.name = "LainHelper";
        md.version = "1.6.x-v40";
        md.authorList = Arrays.asList("zlainsama");
        md.autogenerated = false;
        return md;
    }

    @Subscribe
    public void init(FMLPreInitializationEvent event)
    {
        proxy = event.getSide().isClient() ? new ClientProxy() : new CommonProxy();
        try
        {
            Configuration config = new Configuration(event.getSuggestedConfigurationFile());

            idBlockWaterCube = config.getBlock("blockWaterCube", 0).getInt(0);
            idBlockCobbleCube = config.getBlock("blockCobbleCube", 0).getInt(0);
            customLANPort = config.get(Configuration.CATEGORY_GENERAL, "CustomLANPort", 0).getInt(0);
            enableHelperCommands = config.get(Configuration.CATEGORY_GENERAL, "EnableHelperCommands", false).getBoolean(false);
            overworldHomeOnly = config.get(Configuration.CATEGORY_GENERAL, "OverworldHomeOnly", false).getBoolean(false);
            sunlightDebuff = config.get(Configuration.CATEGORY_GENERAL, "SunlightDebuff", false).getBoolean(false);
            vampirePower = config.get(Configuration.CATEGORY_GENERAL, "VampirePower", false).getBoolean(false);
            killingSwords = config.get(Configuration.CATEGORY_GENERAL, "KillingSwords", false).getBoolean(false);

            config.save();
        }
        catch (Exception e)
        {
            event.getModLog().severe(String.format("ERROR loading config: %s", e.toString()));
        }
    }

    @Subscribe
    public void load(FMLInitializationEvent event)
    {
        Cheater.class.getSimpleName();
        proxy.load(event);
    }

    @Subscribe
    public void onServerStarting(FMLServerStartingEvent event)
    {
        proxy.onServerStarting(event);
    }

    @Subscribe
    public void onServerStopping(FMLServerStoppingEvent event)
    {
        proxy.onServerStopping(event);
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller)
    {
        bus.register(this);
        return true;
    }

}
